### ISSUE TITLE
Monitor big changes in Validator commission

### ISSUE THREAD

**Issue by ccris02** [Nadro-J/py-subalert#1]
Would it be possible to implement a bot that monitors big changes in commission. Let's say Validators changes commission from 0% to 20% or higher or +20% change in commission.

**Comment by Nadro-J** [comment]
Should be possible :) leave it with me

**Comment by Nadro-J** [comment]
Now able to capture the difference in validators commission. (The example below is just a test done by changing some values in the cache file.) 

will finalize and deploy later tonight and hopefully we see some alerts come through to Twitter :)

![image](https://user-images.githubusercontent.com/43568466/125942063-ae24d91e-b2eb-40d3-803d-19f9c0097f7b.png)

**Comment by Nadro-J** [comment]
setting up cronjob to run every 24hrs to monitor validators commission, will leave this for a few days and iron out any issues along the way. :)

https://github.com/Nadro-J/py-subalert/blob/main/subalert/validator.py

**Comment by ccris02** [comment]
Maybe 1% in commission change is good for Polkadot but for Kusama its to small. We may get too many notifications for 1% change maybe changing to to anything above 11% would be good. Let me know how that turns out.

**Comment by Nadro-J** [comment]
Will do :) currently it's set to alert on anything, even 0.01% change but that's just until I know it works without running it manually. After that I'll set some parameters to only alert if the change is greater than the a value set in the yaml file :)

Job is scheduled to run tonight at 00:00am UK (only on https://twitter.com/PolkadotTxs at the moment).

**Comment by Nadro-J** [comment]
![image](https://user-images.githubusercontent.com/43568466/126410115-d5ffc2e2-00ba-465b-b389-48aa66d52cf2.png)
Success! making some changes to also add in [1KV] beside validators that are part of the Thousand Validator Programme and also % differences where it'll only alert if it's been raised by a certain threshold.
