### ISSUE TITLE
Change Kusama w

### ISSUE THREAD

**Issue by ccris02** [Nadro-J/py-subalert#5]
I think that changing some threshold would be nice. 
Sending $500k triggers on Polkadot but on Kusama it triggers at $220k

# PolkadotTxs
 ```
transact_threshold: 25000 to 10000
whale_threshold: 500000
```
DOT price $20 x 500,000 = $10mil

# KusamaTxs
  ```
transact_threshold: 1000
  whale_threshold: 250000 to 50000
```
KSM price $220 x 250,000 = $55mil
Whale on KSM should be close to Whale on DOT
KSM price $220 x 50,000 = $11mil

**Comment by Nadro-J** [comment]
Sounds good, the feedback is greatly appreciated :) I'll get this implemented.

I'm going to change the threshold so it doesn't reflect how much DOT/KSM is being transferred but the USD value instead. So I'll set both at $10M for whale threshold and $250k for transactions.

**Comment by ccris02** [comment]
Sounds great. Had some ideas, do you have discord or element chat?

**Comment by Nadro-J** [comment]
I have a discord setup :) discord.gg/42xbyQBtwS

**Comment by Nadro-J** [comment]
Implementing this today :)

**Comment by Nadro-J** [comment]
Complete. Transaction alert is now set at $200k and based on actual USD value rather than total amount of DOT/KSM.
